### ISSUE TITLE
errors : all tensors must be on devices[0]

### ISSUE THREAD

**Issue by sijun-zhou** [open-mmlab/mmaction#141]
Hi.
I have two titan xp on my single machine.  
i run the command as below. all other settings as github provided without any changes:
**./tools/dist_test_recognizer.sh configs/ucf101/tsn_rgb_bninception.py ./modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 2**

result:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 188, in <module>
    main()
  File "./tools/test_recognizer.py", line 160, in main
    model = MMDistributedDataParallel(model.cuda(), device_ids=[0,1])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/distributed.py", line 300, in __init__
    self._ddp_init_helper()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/distributed.py", line 318, in _ddp_init_helper
    self._module_copies = replicate(self.module, self.device_ids, detach=True)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/replicate.py", line 96, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/replicate.py", line 75, in _broadcast_coalesced_reshape
    return comm.broadcast_coalesced(tensors, devices)
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
**RuntimeError: all tensors must be on devices[0]**
rank 0, data_batch 0
start inferece ...
Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 188, in <module>
    main()
  File "./tools/test_recognizer.py", line 162, in main
    outputs = multi_test(model, data_loader)
  File "./tools/test_recognizer.py", line 44, in multi_test
    result = model(return_loss=False, **data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/distributed.py", line 445, in forward
    output = self.gather(outputs, self.output_device)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/distributed.py", line 472, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './tools/test_recognizer.py', '--local_rank=1', 'configs/ucf101/tsn_rgb_bninception.py', './modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth', '--launcher', 'pytorch']' returned non-zero exit status 1

**anyone that can help me to solve this out? appreciate your help!**

BTW. i can run the inference using one gpu with no errors as below:
CUDA_VISIBLE_DEVICES=0 ./tools/dist_test_recognizer.sh **configs/ucf101/tsn_rgb_bninception.py ./modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 1**

**Comment by zhaoyue-zephyrus** [comment]
Hi @sijun-zhou 

This is because of a recent upgrade of mmcv (See https://github.com/open-mmlab/mmcv/pull/188). Could you please downgrade your mmcv via `pip install mmcv==0.2.16` as a workaround?

We should provide an upgrade alongwith mmcv recently.

Yue

**Comment by sijun-zhou** [comment]
> Hi @sijun-zhou
> 
> This is because of a recent upgrade of mmcv (See [open-mmlab/mmcv#188](https://github.com/open-mmlab/mmcv/pull/188)). Could you please downgrade your mmcv via `pip install mmcv==0.2.16` as a workaround?
> 
> We should provide an upgrade alongwith mmcv recently.
> 
> Yue

Thanks @zhaoyue-zephyrus . The problem solves. And i can see the result is a 101 length list.

btw.
is the output at the begining correct?

**_"The model and loaded state dict do not match exactly"
unexpected key in source state_dict: fc.weight, fc.bias_**

**Comment by zhaoyue-zephyrus** [comment]
This output is a verbose warning. It appears when loading backbone network with a pretrained weight. You can simply ignore that since it reloads a newer weight (`**.pth` in your args) afterwards.

**Comment by sijun-zhou** [comment]
hi @zhaoyue-zephyrus ,
still need to trouble you!
configuaration as i described above-two xp gpus on one machine. But after i do the above changes you descirbed(downgrad mmcv), new problem appears. 

After i run dist_test_recognizer.sh , i use command 'watch -n 0.3 nvidia-smi'. i see gpu0's utilization ups and down(it seems correct), but gpu1's  utilization always stucks at 100% .

and the output is shown as below(only one output related to rank1):

./tools/dist_test_recognizer.sh configs/ucf101/tsn_rgb_bninception.py modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 2
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

rank 0, data_batch 0
rank 1, data_batch 0
rank 0, data_batch 100
rank 0, data_batch 200
rank 0, data_batch 300
rank 0, data_batch 400
rank 0, data_batch 500
rank 0, data_batch 600
rank 0, data_batch 700
rank 0, data_batch 800
rank 0, data_batch 900
rank 0, data_batch 1000
rank 0, data_batch 1100
rank 0, data_batch 1200
rank 0, data_batch 1300
rank 0, data_batch 1400
rank 0, data_batch 1500
rank 0, data_batch 1600
rank 0, data_batch 1700
rank 0, data_batch 1800
rank 0, begin collect results
rank 0 begin dump
rank 0 finished dump

**_program stuck at this point for nearly 40 minutes without changes! and now two gpus's utilization are always 100%. It seems all stuck now._**

Thu Mar 12 23:48:27 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:03:00.0  On |                  N/A |
| 37%   62C    P2    90W / 250W |  10485MiB / 12188MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:04:00.0 Off |                  N/A |
| 38%   65C    P2    89W / 250W |    879MiB / 12196MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1295      G   /usr/lib/xorg/Xorg                           355MiB |
|    0      6181      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files    94MiB |
|    0      8106      G   /opt/teamviewer/tv_bin/TeamViewer             11MiB |
|    0      8404      G   ...sine/work/pycharm-2019.3.3/jbr/bin/java    35MiB |
|    0      8419      G   compiz                                       195MiB |
|    0     22605      C   /usr/bin/python3                            9789MiB |
|    1     22606      C   /usr/bin/python3                             867MiB |
+-----------------------------------------------------------------------------+

**Comment by sijun-zhou** [comment]
@zhaoyue-zephyrus 
the problem above does not frequently happen. I run the program another two times without any program complain. So, this is not a frequent problem.

**Comment by ciwei123** [comment]
@sijun-zhou @zhaoyue-zephyrus I also meet the same problem, did you solve it?

**Comment by sijun-zhou** [comment]
> @sijun-zhou @zhaoyue-zephyrus I also meet the same problem, did you solve it?

which problem? the problem for all tensors must be on device[0]? or the problem some times gpus stucks at data batch0?

**Comment by ciwei123** [comment]
> > @sijun-zhou @zhaoyue-zephyrus I also meet the same problem, did you solve it?
> 
> which problem? the problem for all tensors must be on device[0]? or the problem sometimes gpu stucks at data batch0?

the problem sometimes gpu stucks at data batch0,

**Comment by sijun-zhou** [comment]
> > > @sijun-zhou @zhaoyue-zephyrus I also meet the same problem, did you solve it?
> > 
> > 
> > which problem? the problem for all tensors must be on device[0]? or the problem sometimes gpu stucks at data batch0?
> 
> the problem sometimes gpu stucks at data batch0,

no i doesn't work it out. this problem will disappear when i run the script the second or third time.

**Comment by ciwei123** [comment]
@sijun-zhou @zhaoyue-zephyrus Thanks for your reply.  The output is shown as below:

 ./tools/dist_test_recognizer.sh ./test_configs/TSN/tsn_kinetics400_2d_rgb_r50_seg3_f1s1.py ./modelzoo/tsn2d_kinetics400_rgb_r50_seg3_f1s1-b702e12f.pth 8

rank 7, data_batch 0
rank 0, data_batch 0
rank 5, data_batch 0
rank 6, data_batch 0
rank 1, data_batch 0
rank 2, data_batch 0
rank 4, data_batch 0
rank 3, data_batch 0

program stuck at this point without changes! and 4 gpus's utilization are always 100%. It seems all stuck now.And I run the script multiple times and the same situation occurs. Looking forward to your reply.

**Comment by ciwei123** [comment]
> @sijun-zhou @zhaoyue-zephyrus Thanks for your reply. The output is shown as below:
> 
> ./tools/dist_test_recognizer.sh ./test_configs/TSN/tsn_kinetics400_2d_rgb_r50_seg3_f1s1.py ./modelzoo/tsn2d_kinetics400_rgb_r50_seg3_f1s1-b702e12f.pth 8
> 
> rank 7, data_batch 0
> rank 0, data_batch 0
> rank 5, data_batch 0
> rank 6, data_batch 0
> rank 1, data_batch 0
> rank 2, data_batch 0
> rank 4, data_batch 0
> rank 3, data_batch 0
> 
> program stuck at this point without changes! and 4 gpus's utilization are always 100%. It seems all stuck now.And I run the script multiple times and the same situation occurs. Looking forward to your reply.

I have solved it .The mmcv version I used before was 0.2.15 and it was just fine after changing to 0.2.16.

**Comment by sijun-zhou** [comment]
> > @sijun-zhou @zhaoyue-zephyrus Thanks for your reply. The output is shown as below:
> > ./tools/dist_test_recognizer.sh ./test_configs/TSN/tsn_kinetics400_2d_rgb_r50_seg3_f1s1.py ./modelzoo/tsn2d_kinetics400_rgb_r50_seg3_f1s1-b702e12f.pth 8
> > rank 7, data_batch 0
> > rank 0, data_batch 0
> > rank 5, data_batch 0
> > rank 6, data_batch 0
> > rank 1, data_batch 0
> > rank 2, data_batch 0
> > rank 4, data_batch 0
> > rank 3, data_batch 0
> > program stuck at this point without changes! and 4 gpus's utilization are always 100%. It seems all stuck now.And I run the script multiple times and the same situation occurs. Looking forward to your reply.
> 
> I have solved it .The mmcv version I used before was 0.2.15 and it was just fine after changing to 0.2.16.

yes. i am using mmcv 0.2.16. But sometimes, not every time, also meet such problem.

**Comment by akashsharma29** [comment]
@sijun-zhou @zhaoyue-zephyrus @ciwei123 
I was initially facing the same error: **all tensors must be on devices[0]**
This has been resolved with the MMCV version 0.2.16. Now, I am getting the below output and the program does not do anything for a long time. Did you guys get the same output logs? Also, where should I see the 101 length list if it is running properly? I am not getting any error as such.
[
![Github](https://user-images.githubusercontent.com/36917739/77192819-2f13cc80-6aab-11ea-9239-74d78bdac8b6.png)
](url)

**Comment by ciwei123** [comment]
> does not do anything for a long time. Did you guys get the same output logs? Also, where should I see the 101 length list if it is running properly? I am not getting any error as such.

The output is shown as follow:
./tools/dist_test_recognizer.sh test_configs/TSN/ucf101/tsn_rgb_bninception.py modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 8
rank 4, data_batch 0
rank 3, data_batch 0
rank 5, data_batch 0
rank 6, data_batch 0
rank 7, data_batch 0
rank 2, data_batch 0
rank 1, data_batch 0
rank 0, data_batch 0
rank 0, data_batch 100
rank 0, data_batch 200
rank 0, data_batch 300
rank 0, data_batch 400
rank 0, begin collect results
rank 0 begin dump
rank 0 finished dump
program stuck at this point without changes! and 8 gpus's utilization are always 100%. It seems all stuck now.I thought I solved the problem by changing the version, but it didn't. And Runs normally when using a GPU, I suspect it is a problem with distributed running.My configuration information：
mmcv 0.2.16
pytorch 1.1.0
cuda  10.0.130
gpu driver 418.39
opencv 4.1.0
python 3.5.2
gcc 5.4.0
ffmpeg 4.2.2
@zhaoyue-zephyrus Could you tell me your configuration information?Thank you very much!

**Comment by ciwei123** [comment]
@sijun-zhou @zhaoyue-zephyrus @loveunk @akashsharma29 When I test the I3D model, I found that the name of the data read by each GPU is the same. Have you encountered the same situation and would you tell me how to solve it? Is this the reason why the program is stuck？Thanks.

**Comment by cinjon** [comment]
I also ran into the initial problem above, but have changed mmcv a bit so reverting to a prior version wasn't ideal. I changed 

`model = MMDistributedDataParallel(model.cuda())`

to

```
model = MMDistributedDataParallel(
    model.cuda(),
    device_ids=[torch.cuda.current_device()],
    broadcast_buffers=False)
```

like suggested and it _seems_ to be working properly. @zhaoyue-zephyrus, anything I should know about that might be an issue still?

**Comment by xianguo-dev** [comment]
@zhaoyue-zephyrus Hi! Would you please provide the code to generate "normalized_proposal_list.txt" for I find so many people like me are struggling on this problem.
